"""Central configuration: event taxonomy, encoder registry, generation prompts, paths.

Edit this file rather than hard-coding constants elsewhere. Everything downstream
(manifest, embedding, evaluation, bridging) reads from here.
"""
from __future__ import annotations
import os
from pathlib import Path

# --------------------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------------------
# Heavy artifacts (raw audio, embeddings) live OUTSIDE the (Dropbox-synced) code tree and
# are relocatable so the same manifest works locally and on a Modal volume:
#   SMSR_DATA  -> root for manifest/embeddings/results/synth   (default: <repo>/data)
#   SMSR_RAW   -> root that manifest `path` columns are RELATIVE to (the extracted corpora)
#                 (default: SMSR_DATA/raw).  On Modal set SMSR_RAW=/data/raw/extracted.
ROOT = Path(__file__).resolve().parent
DATA = Path(os.environ.get("SMSR_DATA", ROOT / "data"))
RAW = DATA / "raw"               # downloaded source corpora (DCASE T7, FSD50K, ESC-50, ...)
RAW_ROOT = Path(os.environ.get("SMSR_RAW", RAW))  # manifest paths are relative to this
SYNTH = DATA / "synth"           # generated synthetic clips
EMB = DATA / "embeddings"        # cached .npy embedding matrices, one per encoder
# the single source of truth: one row per clip. SMSR_MANIFEST switches corpora
# (e.g. manifest_ucs.csv for the diverse UCS corpus) without touching downstream code.
MANIFEST = Path(os.environ.get("SMSR_MANIFEST", DATA / "manifest.csv"))
RESULTS = ROOT / "results"       # small JSON/figures -> keep in the code tree
for d in (DATA, RAW, SYNTH, EMB, RESULTS):
    d.mkdir(parents=True, exist_ok=True)


def resolve_audio_path(rel_or_abs: str) -> Path:
    """Resolve a manifest `path` (relative to RAW_ROOT, or already absolute)."""
    p = Path(rel_or_abs)
    return p if p.is_absolute() else (RAW_ROOT / p)

# Target audio spec for the benchmark (everything is resampled/normalised to this).
TARGET_SR = 48_000               # CLAP expects 48 kHz; encoders resample internally as needed
CLIP_SECONDS = 5.0               # pad/trim every clip to a fixed window <= 5 s
MONO = True

# --------------------------------------------------------------------------------------
# Event taxonomy
# --------------------------------------------------------------------------------------
# Tier 1 == the 7 DCASE-2023 Task-7 classes (real + synthetic already aligned, ready to use).
DCASE7 = [
    "dog_bark", "footstep", "gunshot", "keyboard",
    "moving_motor_vehicle", "rain", "sneeze_cough",
]
# Tier 2 == extension classes for breadth (real from FSD50K/ESC-50, synthetic generated by us).
# Chosen to span impact/transient, texture/noise, tonal/music, and mechanical sounds so the
# benchmark is not dominated by one acoustic morphology.
EXTENSION = [
    "glass_break", "door_knock", "water_pouring", "fire_crackle",
    "applause", "clock_tick", "camera_shutter", "bell_ring",
    "engine_idle", "wind", "piano_note", "drum_hit",
]
EVENT_CLASSES = DCASE7 + EXTENSION

# Coarse acoustic morphology grouping (used for stratified analysis in the paper).
MORPHOLOGY = {
    "transient": ["gunshot", "glass_break", "door_knock", "clock_tick",
                  "camera_shutter", "drum_hit", "footstep"],
    "texture":   ["rain", "water_pouring", "fire_crackle", "wind", "applause"],
    "tonal":     ["piano_note", "bell_ring"],
    "mechanical": ["keyboard", "moving_motor_vehicle", "engine_idle"],
    "vocal_animal": ["dog_bark", "sneeze_cough"],
}

# --------------------------------------------------------------------------------------
# Text-to-audio generation prompts (for synthesising the "synthetic" domain).
# Multiple templates per class -> prompt diversity. {var} slots are filled at generation
# time from the lists below to avoid a single canned phrasing per class.
# --------------------------------------------------------------------------------------
PROMPT_TEMPLATES = [
    "{adj} {event_phrase}, isolated sound effect, no music",
    "a {event_phrase}, clean foley recording, dry",
    "{event_phrase}, close-mic sound effect, mono",
    "the sound of {event_phrase}, studio foley",
]
PROMPT_ADJECTIVES = ["clear", "realistic", "high quality", "crisp", "natural"]
# Human-readable event phrases for prompting (kept separate from machine label).
EVENT_PHRASE = {
    "dog_bark": "a dog barking", "footstep": "footsteps on a hard floor",
    "gunshot": "a gunshot", "keyboard": "typing on a computer keyboard",
    "moving_motor_vehicle": "a car driving past", "rain": "steady rain",
    "sneeze_cough": "a person sneezing and coughing", "glass_break": "glass shattering",
    "door_knock": "knocking on a wooden door", "water_pouring": "water pouring into a glass",
    "fire_crackle": "a crackling campfire", "applause": "a crowd applauding",
    "clock_tick": "a clock ticking", "camera_shutter": "a camera shutter click",
    "bell_ring": "a hand bell ringing", "engine_idle": "a car engine idling",
    "wind": "wind blowing", "piano_note": "a single piano note",
    "drum_hit": "a single snare drum hit",
}

# --------------------------------------------------------------------------------------
# Encoder registry. `kind` selects the loader in encoders.py.
# Add a row here to benchmark a new encoder; no other file needs to change.
# --------------------------------------------------------------------------------------
ENCODERS = {
    # --- CLAP (HuggingFace transformers, fully implemented) ---
    "clap_general": {"kind": "clap_hf", "hf_id": "laion/clap-htsat-unfused", "dim": 512, "sr": 48_000},
    "clap_fused":   {"kind": "clap_hf", "hf_id": "laion/clap-htsat-fused",   "dim": 512, "sr": 48_000},
    "clap_music":   {"kind": "clap_laion_ckpt",                              # music+speech+audioset ckpt
                     "amodel": "HTSAT-base",
                     "ckpt": "music_speech_audioset_epoch_15_esc_89.98.pt", "dim": 512, "sr": 48_000},
    # --- self-supervised general audio (loaders are stubs; see encoders.py TODOs) ---
    "beats":    {"kind": "beats",   "ckpt": "BEATs_iter3_plus_AS2M.pt",   "dim": 768, "sr": 16_000},
    "m2d":      {"kind": "m2d",     "ckpt": "m2d_vit_base-80x608p16x16",  "dim": 768, "sr": 16_000},
    "audiomae": {"kind": "audiomae","ckpt": "pretrained.pth",             "dim": 768, "sr": 16_000},
    # --- supervised baselines ---
    "panns_cnn14": {"kind": "panns", "ckpt": "Cnn14_mAP=0.431.pth", "dim": 2048, "sr": 32_000},
    "ast": {"kind": "ast_hf", "hf_id": "MIT/ast-finetuned-audioset-10-10-0.4593", "dim": 768, "sr": 16_000},
}

# Domains and split names (kept as constants to avoid typos across files).
DOMAINS = ("real", "synth")
SPLITS = ("train", "val", "test")

SEED = 1234
